# Generated by Django 3.0.5 on 2020-04-27 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apod', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='owner',
        ),
    ]
