# Generated by Django 3.0.5 on 2020-05-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apod', '0002_auto_20200428_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
