# Generated by Django 3.0.5 on 2020-04-25 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apod', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name']},
        ),
    ]
