# Generated by Django 3.0.5 on 2020-04-25 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apod', '0002_auto_20200425_0437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
    ]
