# Generated by Django 3.0.5 on 2020-04-25 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apod', '0003_auto_20200425_0452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name']},
        ),
    ]
